# Generated by Django 3.0.5 on 2020-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20200503_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpositive',
            name='date_tested',
            field=models.DateField(),
        ),
    ]
