# Generated by Django 3.0.5 on 2020-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200503_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
    ]
