# Generated by Django 3.0.5 on 2020-05-06 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0005_auto_20200504_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('latitude', 'longitude', 'log_start', 'log_end')},
        ),
        migrations.AlterUniqueTogether(
            name='testpositive',
            unique_together={('user', 'date_tested')},
        ),
        migrations.AlterUniqueTogether(
            name='userlog',
            unique_together={('user', 'log')},
        ),
    ]
